#! /usr/bin/env php

<?php 

use Symfony\Component\Console\Application;
use Unlu\CLTodo\Command\ShowCommand;
use Unlu\CLTodo\Command\AddCommand;
use Unlu\CLTodo\Command\RemoveCommand;
use Unlu\CLTodo\Task;

require __DIR__ . '/vendor/autoload.php';

$task = new Task();
$task->createTable();

// Application
$app = new Application('Command Line ToDo App', '1.0');

$app->add(new ShowCommand($task));
$app->add(new AddCommand($task));
$app->add(new RemoveCommand($task));

$app->run();